# version: '3.8'

# This file provides development-specific overrides for our services.
services:
  # --- Frontend Development Overrides ---
  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        APP_NAME: web
      target: builder
    command: pnpm turbo dev --filter=@kbc/web # <-- FIX
    volumes:
      - ./packages/web:/usr/src/app/packages/web
      - /usr/src/app/node_modules
    init: true
    ports:
      - "5173:5173"

  admin-ui:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        APP_NAME: admin-ui
      target: builder
    command: pnpm turbo dev --filter=@kbc/admin-ui # <-- FIX
    volumes:
      - ./packages/admin-ui:/usr/src/app/packages/admin-ui
      - /usr/src/app/node_modules
    init: true
    ports:
      - "5174:5174"

  # --- Backend Development Overrides ---
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        APP_NAME: api-gateway
      target: builder
    command: pnpm turbo dev --filter=@kbc/api-gateway # <-- FIX
    volumes:
      - ./packages/api-gateway:/usr/src/app/packages/api-gateway
      - /usr/src/app/node_modules
      - /usr/src/app/packages/api-gateway/dist
    init: true

  service-auth:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        APP_NAME: service-auth
      target: builder
    command: pnpm turbo dev --filter=@kbc/service-auth # <-- FIX
    volumes:
      - ./packages/service-auth:/usr/src/app/packages/service-auth
      - /usr/src/app/node_modules
      - /usr/src/app/packages/service-auth/dist
    init: true

  service-game:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        APP_NAME: service-game
      target: builder
    command: pnpm turbo dev --filter=@kbc/service-game # <-- FIX
    volumes:
      - ./packages/service-game:/usr/src/app/packages/service-game
      - /usr/src/app/node_modules
      - /usr/src/app/packages/service-game/dist
    init: true

  service-quiz:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        APP_NAME: service-quiz
      target: builder
    command: pnpm turbo dev --filter=@kbc/service-quiz # <-- FIX
    volumes:
      - ./packages/service-quiz:/usr/src/app/packages/service-quiz
      - /usr/src/app/node_modules
      - /usr/src/app/packages/service-quiz/dist
    init: true

  service-analytics:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        APP_NAME: service-analytics
      target: builder
    command: pnpm turbo dev --filter=@kbc/service-analytics # <-- FIX
    volumes:
      - ./packages/service-analytics:/usr/src/app/packages/service-analytics
      - /usr/src/app/node_modules
      - /usr/src/app/packages/service-analytics/dist
    init: true